spring:
  cloud:
    gateway:
      routes:
        - id: test_router
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu9
        - id: qq_router
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: gulimall-product
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
##       前端请求默认路由到renren-fast
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}
